### ISSUE TITLE
Sending _stub_aggregator metrics to carbon cache

### ISSUE THREAD

**Issue by iain-buclaw-sociomantic** [grobian/carbon-c-relay#133]
Since update to v1.2, I'm seeing carbon-c-relay sending e.g: ``_stub_aggregator_0x169a400__`` to carbon after reloading the service (via upstart).

**Comment by iain-buclaw-sociomantic** [comment]
Steps to reproduce.

- routes.conf
```
cluster test
    file
        test.out
    ;

aggregate
        ^test\.
    every 10 seconds
    expire after 30 seconds
    compute sum write to
        aggregates.all.test
    send to test
    stop
    ;

match *
    send to test
    ;
```
- command:
``./relay -f routes.conf -s``
- input:
```
test.foo 0 1450887178
test.bar 1 1450887178
test.baz 2 1450887178
```
Immediately after, invoke ``SIGHUP`` (eg: `` kill -1 `pidof relay` ``)
- output:
```
_stub_aggregator_0x18f09f0__aggregates.all.test 3.000000 1450887180
```

**Comment by iain-buclaw-sociomantic** [comment]
If I were to remove these lines:
```
    send to test
    stop
```
Then the problem goes away.

**Comment by grobian** [comment]
Right, that's due to issue #32. You best restart the relay, instead of reloading it when you use aggregates.

**Comment by grobian** [comment]
This should be fixed now.  Tests welcome.

**Comment by iain-buclaw-sociomantic** [comment]
I can still reproduce it, though it looks like a bit of a racy circumstance? (we receive about 2-3Million metrics a minute, 300-400k of which are processed for aggregation, so everything is a race :-).

Here's the log as it happens (I just put in some printf's so I could better understand what is happening).

```
===
=== Reloading (^test\.(.*)) using route: _stub_aggregator_0xd6fc10__
===
>>> Aggregator received metric: test.foo 123 1451382897
<<< Expiring aggregate metric: _stub_aggregator_0xd6fc10__aggregates.max.test 123.000000 1451382900
>>> Enqueuing: _stub_aggregator_0xd6fc10__aggregates.max.test 123.000000 1451382900
<<< Dequeuing: _stub_aggregator_0xd6fc10__aggregates.max.test 123.000000 1451382900
<<< Writing to pipe(10): _stub_aggregator_0xd6fc10__aggregates.max.test 123.000000 1451382900
>>> Enqueuing: aggregates.max.test 123.000000 1451382900
<<< Dequeuing: aggregates.max.test 123.000000 1451382900
<<< Writing to file(11): aggregates.max.test 123.000000 1451382900
[2015-12-29 10:55:05] caught SIGHUP...
[2015-12-29 10:55:05] reloading config from 'routes.conf'
===
=== Reloading (^test\.(.*)) using route: _stub_aggregator_0xd2b9d0__
===
[2015-12-29 10:55:05] reloading collector
[2015-12-29 10:55:06] interrupting workers
[2015-12-29 10:55:06] expiring aggregations
<<< Expiring aggregate metric: _stub_aggregator_0xd6fc10__aggregates.sum.test 123.000000 1451382900
>>> Enqueuing: _stub_aggregator_0xd6fc10__aggregates.sum.test 123.000000 1451382900
[2015-12-29 10:55:06] reloading workers
[2015-12-29 10:55:06] SIGHUP handler complete
<<< Dequeuing: _stub_aggregator_0xd6fc10__aggregates.sum.test 123.000000 1451382900
<<< Writing to pipe(10): _stub_aggregator_0xd6fc10__aggregates.sum.test 123.000000 1451382900
>>> Enqueuing: _stub_aggregator_0xd6fc10__aggregates.sum.test 123.000000 1451382900
<<< Dequeuing: _stub_aggregator_0xd6fc10__aggregates.sum.test 123.000000 1451382900
<<< Writing to file(11): _stub_aggregator_0xd6fc10__aggregates.sum.test 123.000000 1451382900
```
All I can conclude is that either all aggregates should be expired before reloading the config, or some other kind of identifier should be used that is persistent across reloads.

**Comment by grobian** [comment]
there is a thinko, we need to avoid new metrics coming in, but the aggregator behaves as a regular client to the relay, so its metrics aren't processed as well.

**Comment by grobian** [comment]
I believe I finally cracked this problem.

**Comment by iain-buclaw-sociomantic** [comment]
Yes, I can't seem to reproduce in the simple case anymore. :+1:

**Comment by grobian** [comment]
That's good news!
